### ISSUE TITLE
Difference between source and tutorial

### ISSUE THREAD

**Issue by Yippikai** [gonzad77/angular6-firebase-crud#4]
Hi,
The tutorial (https://angular-templates.io/tutorials/about/angular-crud-with-firebase) and source code does not seems to match any more.

Additionally I got error 'app$$1.firestore is not a function' when I try to open it in 'https://stackblitz.com/github/AngularTemplates/angular-firebase-crud'

**Comment by Yippikai** [comment]
Actually I have solved the last part by changing the  dependencies to "@angular/fire": "^5.2",
(which includes dependencies to firebase component as well).

**Comment by djabif** [comment]
thanks for your feedback. we will update the tutorial soon.
